const ORIGIN = "https://app.blackbox.ai";
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36 Edg/149.0.0.0";
const FALLBACK_VALIDATED = "a38f5889-8fef-46d4-8ede-bf4668b6a9bb";
const ANCHOR = /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})";function detectVscode/;
const WRAP_SYSTEM = "Wrap your entire reply between <answer> and </answer> tags. Write nothing outside these tags.";
const OPEN_TAG = /^(?:<answer>|answer>|nswer>|swer>|wer>|er>|r>|>)\s*/;
const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "POST, OPTIONS", "Access-Control-Allow-Headers": "Content-Type" };

let cachedValidated = FALLBACK_VALIDATED;

function randomId(len = 7) {
  const c = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let s = "";
  for (let i = 0; i < len; i++) s += c[Math.floor(Math.random() * c.length)];
  return s;
}

function isRejected(raw) {
  return /Generated by BLACKBOX\.AI|not upgraded your account/i.test(raw);
}

function parseAnswer(raw) {
  const think = [];
  let body = raw.replace(/<think>([\s\S]*?)<\/think>/g, (_, t) => { think.push(t.trim()); return ""; });
  const end = body.indexOf("</answer>");
  if (end !== -1) body = body.slice(0, end).trimStart().replace(OPEN_TAG, "");
  return { text: body.trim(), think: think.join("\n\n").trim() || null };
}

async function fetchValidated() {
  const headers = { "user-agent": UA };
  const html = await fetch(`${ORIGIN}/`, { headers }).then(r => r.text()).catch(() => "");
  const chunks = [...new Set([...html.matchAll(/\/_next\/static\/[^"]+\.js/g)].map(m => m[0]))];
  const found = await Promise.all(chunks.map(c =>
    fetch(`${ORIGIN}${c}`, { headers }).then(r => r.text()).then(js => (js.match(ANCHOR) || [])[1] || null).catch(() => null)
  ));
  return found.find(Boolean) || null;
}

function buildPayload(messages, validated, options = {}) {
  const { webSearch = false, agent = "VscodeAgent", maxTokens = 1024 } = options;
  return {
    messages,
    id: messages[messages.length - 1].id,
    userSelectedAgent: agent,
    userSelectedModel: null,
    maxTokens,
    validated,
    clickedForceWebSearch: webSearch,
    webSearchModeOption: { autoMode: !webSearch, webMode: webSearch, offlineMode: false },
    codeModelMode: true,
    isPremium: false
  };
}

async function doRequest(payload) {
  const res = await fetch(`${ORIGIN}/api/chat`, {
    method: "POST",
    headers: { "content-type": "application/json", "origin": ORIGIN, "referer": `${ORIGIN}/chat`, "user-agent": UA },
    body: JSON.stringify(payload)
  });
  return res.text();
}

module.exports = async (req, res) => {
  Object.entries(cors).forEach(([k, v]) => res.setHeader(k, v));
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const { prompt, history = [], webSearch = false } = req.body || {};
  if (!prompt) return res.status(400).json({ error: "prompt required" });

  const userMsg = { id: randomId(), role: "user", content: String(prompt) };
  const wrapped = [{ id: randomId(), role: "system", content: WRAP_SYSTEM }, ...history, userMsg];

  try {
    let raw = await doRequest(buildPayload(wrapped, cachedValidated, { webSearch }));

    if (isRejected(raw)) {
      const fresh = await fetchValidated();
      if (fresh && fresh !== cachedValidated) {
        cachedValidated = fresh;
        raw = await doRequest(buildPayload(wrapped, cachedValidated, { webSearch }));
      }
    }

    if (isRejected(raw)) return res.status(502).json({ ok: false, error: "Blackbox rejected request" });

    const { text, think } = parseAnswer(raw);
    return res.status(200).json({
      ok: true,
      text,
      think,
      history: [...history, userMsg, { id: randomId(), role: "assistant", content: text }]
    });
  } catch (err) {
    return res.status(500).json({ ok: false, error: err.message });
  }
};
